# Generated by Django 3.2.7 on 2021-09-13 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no photo title', max_length=100)),
                ('album', models.CharField(default='no album title', max_length=100)),
                ('preview_url', models.CharField(max_length=200, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='okay.artist')),
            ],
        ),
    ]
